#pragma once
#include <aclops/binary_op_acl.h>
#include <aclops/clamp_op_acl.h>
#include <aclops/unary_op_acl.h>
#include <aclops/conv_op_acl.h>
#include <aclops/ternary_op_acl.h>
#include <aclops/reduce_op_acl.h>
#include <aclops/truth_reduce_op_acl.h>
#include <aclops/arg_reduce_op_acl.h>
#include <aclops/expand_op_acl.h>
#include <aclops/getitem_op_acl.h>
#include <aclops/setitem_op_acl.h>
#include <aclops/matmul_op_acl.h>
#include <aclops/random_op_acl.h>
#include <aclops/bmm_op_acl.h>
#include <aclops/pool_op_acl.h>
#include <aclops/flip_op_acl.h>
#include <aclops/roll_op_acl.h>
#include <aclops/concat_op_acl.h>
#include <aclops/gather_scatter_op_acl.h>
#include <aclops/cumsum_op_acl.h>
#include <aclops/index_op_acl.h>
#include <aclops/where_op_acl.h>
#include <aclops/floor_op_acl.h>
#include <aclops/transpose_op_acl.h>
#include <aclops/flashattention_op_acl.h>
#include <aclops/relu_op_acl.h>
#include <aclops/dropout_op_acl.h>
#include <aclops/silu_op_acl.h>
#include <aclops/gelu_op_acl.h>
#include <aclops/sigmoid_op_acl.h>
#include <aclops/softmax_op_acl.h>
#include <aclops/stack_op_acl.h>
#include <aclops/nantonum_op_acl.h>
#include <aclops/rope_op_acl.h>
#include <aclops/triu_op_acl.h>
#include <aclops/embedding_op_acl.h>
#include <aclops/norms_op_acl.h>
#include <aclops/upsample_op_acl.h>
#include <aclops/adamw_op_acl.h>
#include <aclops/fused_sgd_op_acl.h>
