blank_issues_enabled: false
contact_links:
  - name: Jittor 论坛
    url: https://discuss.jittor.cn/
    about: 一般性讨论和问答请前往 Jittor 论坛
  - name: Jittor 文档
    url: https://cg.cs.tsinghua.edu.cn/jittor/assets/docs/index.html
    about: 请先查阅官方文档
