// ***************************************************************
// Copyright (c) 2023 Jittor. All Rights Reserved. 
// Maintainers: Dun Liang <randonlang@gmail.com>. 
// This file is subject to the terms and conditions defined in
// file 'LICENSE.txt', which is part of this source code package.
// ***************************************************************
#pragma once
#include "common.h"
#include "misc/nano_string.h"
#include "misc/nano_vector.h"

namespace jittor {

EXTERN_LIB unordered_map<void*, int64> lived_nodes;
EXTERN_LIB unordered_map<int64, Node*> lived_nodes_id;
EXTERN_LIB int64 total_node;
EXTERN_LIB int free_buffer_depth;
EXTERN_LIB vector<Node*> free_buffer;
EXTERN_LIB uint8 node_order;
// Non-zero while lived_nodes is being maintained in a build without
// NODE_MEMCHECK; set by check_graph's setter (graph.cc).
EXTERN_LIB int node_track_lived;

inline static Node* get_node(int64 id) 
{ return  lived_nodes_id.count(id) ? lived_nodes_id[id] : nullptr; }

// A node's flag word is a union: bits 0..5 mean the same thing whatever the
// node is, and everything above that means one thing on a Var and a different
// thing on an Op. That is fine as a layout and was a hazard as an interface --
// the two enums were written into one list of hand-picked numbers, so
// `_explicit_requires_grad` and `_is_scalar` were both "11" for a while and every
// requires_grad_(True) parameter read back as a Python scalar (dtype promotion
// dropped it, AMP skipped it). The numbers below are generated by the enums
// instead of chosen, the static_asserts at the bottom of this block prove the
// shared bits do not land inside either private layout, and a kind-private bit
// can only be reached through `Var::flag`/`Op::flag`, so reading one off a bare
// `Node*` does not compile.

// The bits every node kind carries.
struct NodeBits {
    enum Flags {
        _var = 0,
        _finished,
        _stop_grad,
        _fetch,
        // 2 bits, low first: see Node::order().
        _node_order_low,
        _node_order_high,
        // First bit whose meaning depends on the kind of node. Nothing below
        // this is private; nothing at or above it is shared until
        // NodeFlags::_shared_high (which is generated, see below).
        _kind_private,
    };
    static constexpr int _node_order_nbits = 2;
};

// Var-private bits, numbered consecutively upward from the shared range.
// Add new ones before `_end`; never write a number here.
struct VarFlags {
    enum Flags {
        _force_fuse = NodeBits::_kind_private,
        _stop_fuse,
        // The producer of this var is needed to compute a gradient.
        _needed_by_backward,
        _out_hint,
        // requires_grad, as the user set it explicitly.
        _explicit_requires_grad,
        _is_swapped,
        // A Python scalar rather than a 0-d tensor: it does not take part in
        // dtype promotion. Distinct from _explicit_requires_grad -- they shared a bit
        // once, see the comment above.
        _is_scalar,
        // This var depends on a gradient whose producer supports first order
        // only, so a second-order backward through it must be refused.
        _first_order_only,
        // Set with _stop_grad when a backward released the graph
        // (grad.cc, retain_graph=false). _stop_grad alone cannot be told apart
        // from the user's own x.stop_grad(), and a second backward walking into
        // a released var used to hand back a zero gradient without a word.
        _graph_freed,
        // Reversible torch-style requires_grad_(False). Unlike _stop_grad this
        // must not release an already-built backward graph.
        _requires_grad_disabled,
        _end,
    };
};

// Op-private bits. Same rule: consecutive, generated, never hand-numbered.
struct OpFlags {
    enum Flags {
        _cpu = NodeBits::_kind_private,
        _cuda,
        _forwarded,
        _vary_shape,
        // 2 bits: OpType.
        _op_type,
        _op_type_high,
        // backprop grad at ones
        _grads,
        _has_gopt,
        _has_vary_input,
        _manual_set_vnbb,
        // The op places its outputs on a device of its own choosing
        // (device_copy), so Op::init must not overwrite Var::device_id from
        // the inputs.
        _manual_device,
        // Its outputs must remain pending until a later graph-wiring step adds
        // their control edges. TapeOp uses this while Tapes is assembled.
        _must_stay_pending,
        // Six consecutive bits mirroring amp_reg; op.cc writes them and
        // grad.cc reads them back as one field. Only the first three have
        // names, but all six belong to amp -- hence the placeholders, which
        // are what stops the next flag from landing inside the field.
        _prefer_32,
        _prefer_16,
        _reduce_keep,
        _amp_reserved_3,
        _amp_reserved_4,
        _amp_reserved_5,
        _custom_flag,
        // Op meaning of the shared *name*: the op owns frozen edge snapshots
        // of its requires-grad-disabled inputs. Nothing to do with the Var bit
        // of the same name, which is why they are in different enums now.
        _requires_grad_disabled,
        _requires_grad_snapshot,
        _end,
    };
    static constexpr int _op_type_nbits = NodeBits::_node_order_nbits;
    // The width op.cc and grad.cc pass amp_reg through.
    static constexpr int _amp_nbits = 6;
};

struct NodeFlags {
    typedef uint32 nf_t;
    nf_t flags=0;

    enum Flags {
        _var = NodeBits::_var,
        _finished = NodeBits::_finished,
        _stop_grad = NodeBits::_stop_grad,
        _fetch = NodeBits::_fetch,
        _node_order_low = NodeBits::_node_order_low,
        _node_order_high = NodeBits::_node_order_high,
        _n = NodeBits::_kind_private,

        // Shared bits that have to live *above* both private layouts. Generated
        // from the two `_end`s rather than picked by hand: the old comment
        // "bit 28 is free in both layouts" was a claim nothing checked, and the
        // claim was what a new Var-only flag would quietly break.
        _shared_high = ((int)VarFlags::_end > (int)OpFlags::_end)
            ? (int)VarFlags::_end : (int)OpFlags::_end,
        // Set when this node was entered into lived_nodes (see Node::Node).
        // The registry is filled either by a NODE_MEMCHECK build or, in an
        // ordinary build, from the moment check_graph is switched on; the
        // destructor needs to know which nodes it has to take back out. Ops
        // are swept too, so this cannot be a Var-only bit.
        _lived_tracked = _shared_high,
        // This node is already queued for deletion by the outermost
        // SetupFreeBuffer. It used to borrow tflag and a process-global epoch.
        _queued_for_free,
        // VarRelay released this node's liveness accounting without destroying
        // it; graph checking must not report that state as a dangling node.
        _released,
        _shared_high_end,
    };
    static constexpr int _node_order_nbits = NodeBits::_node_order_nbits;

    inline void set(Flags f, int a=1, int nbits=1) {
        set_bit((int)f, a, nbits);
    }

    inline nf_t get(Flags f, int nbits=1) const {
        return get_bit((int)f, nbits);
    }

private:
    // The raw bit operations. Private so that a kind-private flag has to come
    // through Var::flag / Op::flag, which means through a Var* or an Op* --
    // that is the whole point: the flag word cannot say which enum applies,
    // only the static type of the node can.
    friend struct Var;
    friend struct Op;

    inline void set_bit(int f, int a, int nbits) {
        nf_t mask = (((1u<<nbits)-1)<<f);
        flags = (flags & ~mask) | ((a<<f)&mask);
    }

    inline nf_t get_bit(int f, int nbits) const {
        return (flags>>f) & ((1u<<nbits)-1);
    }
};

// The layout invariants the numbering above is supposed to guarantee. Each of
// these was a comment in the previous version, and a comment cannot fail.
static_assert((int)VarFlags::_end <= 32, "Var flags no longer fit in the flag word");
static_assert((int)OpFlags::_end <= 32, "Op flags no longer fit in the flag word");
static_assert((int)NodeFlags::_shared_high_end <= 32,
    "the shared high bits no longer fit in the flag word");
static_assert((int)NodeFlags::_shared_high >= (int)VarFlags::_end,
    "a shared flag bit aliases a Var-only bit");
static_assert((int)NodeFlags::_shared_high >= (int)OpFlags::_end,
    "a shared flag bit aliases an Op-only bit");
static_assert((int)VarFlags::_force_fuse == (int)NodeFlags::_n
    && (int)OpFlags::_cpu == (int)NodeFlags::_n,
    "the private layouts must both start where the shared range ends");
static_assert((int)OpFlags::_custom_flag == (int)OpFlags::_prefer_32 + OpFlags::_amp_nbits,
    "the six amp bits op.cc and grad.cc move as one field are no longer contiguous");
static_assert((int)OpFlags::_op_type_high == (int)OpFlags::_op_type + 1,
    "OpType is read as two bits and they are no longer adjacent");
static_assert((int)NodeFlags::_node_order_high == (int)NodeFlags::_node_order_low + 1,
    "node_order is read as two bits and they are no longer adjacent");

EXTERN_LIB int64 tflag_count;

// Binding and diagnostic layers may observe node lifetime without making the
// graph data structure depend on either of them. The observer is non-owning;
// the registering layer must unregister it before the observer is destroyed.
struct NodeLifecycleObserver {
    virtual void node_created(Node*) = 0;
    virtual void node_destroyed(Node*) = 0;
    virtual ~NodeLifecycleObserver() = default;
};

EXTERN_LIB NodeLifecycleObserver* node_lifecycle_observer;
NodeLifecycleObserver* set_node_lifecycle_observer(NodeLifecycleObserver* observer);

inline void notify_node_created(Node* node) {
    if (PREDICT_BRANCH_NOT_TAKEN(node_lifecycle_observer != nullptr))
        node_lifecycle_observer->node_created(node);
}

inline void notify_node_destroyed(Node* node) {
    if (PREDICT_BRANCH_NOT_TAKEN(node_lifecycle_observer != nullptr))
        node_lifecycle_observer->node_destroyed(node);
}

struct Node {
    struct input_t;
    struct output_t;
    struct var_output_t {
        Op* op;
        int index;
    };
    struct input_t {
        Node* node;
        list<output_t>::iterator back;
        input_t(Node* n) : node(n) {}
        operator Node*() { return node; }
        operator Op*() { return (Op*)node; }
        operator Var*() { return (Var*)node; }
    };
    struct output_t {
        Node* node;
        list<input_t>::iterator back;
        int index;
        output_t(Node* n, int i) : node(n), index(i) {}
        operator Node*() { return node; }
        operator Op*() { return (Op*)node; }
        operator Var*() { return (Var*)node; }
        operator var_output_t() { return {(Op*)node, index}; }
    };
    NodeFlags flags;
    NanoString ns;
    inline bool is_var() const { return flags.get(NodeFlags::_var); }
    inline bool is_stop_grad() const { return flags.get(NodeFlags::_stop_grad); }
    inline bool is_finished() const { return flags.get(NodeFlags::_finished); }
    // forward_liveness can propergate forward(from input to output)
    // f1. var_holder contrib one forward_liveness
    // f2. var ptr contrib one forward_liveness
    // f3. input(has_grad and f>0) contrib one forward_liveness
    int forward_liveness = 0;
    // forward_liveness can propergate backward(from output to input)
    // b1. var ptr contrib one backward_liveness
    // b2. var holder contrib one backward_liveness
    // b3. output(b>0) contrib one backward_liveness
    int backward_liveness = 0;
    // pending liveness can propergate backward(from output to input)
    // p1: pending and f>0 and b>0 contrib pending_liveness
    // p2: output(p>0 and pending) contrib pending_liveness
    int pending_liveness = 0;
    inline bool need_free()
    { return !pending_liveness && (!forward_liveness || !backward_liveness); }
    
    // Position of this node in the batch Executor::run_sync is currently
    // planning (its index in that run's `ops` or `all_vars`), and the stamp of
    // the batch that wrote it.
    //
    // Written with set_batch_index() and read with batch_index_at(stamp): the
    // reader names the batch it believes it is in, and a mismatch is an
    // assertion rather than another algorithm's number. It used to be
    // `custom_data` below, which had no owner at all.
    //
    // The stamp is its own field rather than `tflag`, which would have been
    // free. tflag is a shared counter that any traversal may restamp, and one
    // does, mid-run: MemoryProfiler::check() is called from inside that very
    // loop and its bfs restamps every node it reaches. Reusing tflag here made
    // the check fire in exactly the case it exists to catch (task 2.03 is the
    // general form of that; this field does not wait for it).
    int64 batch_stamp = 0;
    int batch_index = 0;
    inline void set_batch_index(int64 stamp, int index) {
        batch_stamp = stamp;
        batch_index = index;
    }
    // Out of line on purpose. Spelled as `ASSERT(...) << "..."` inline, the
    // failure path's code sits in every one of the executor's tight fusion
    // loops and costs ~0.09 us per op even though it never runs -- measured,
    // 2.30 ms -> 2.51 ms on a 2400-op graph. A predicted-not-taken branch to a
    // cold function is the same check for none of that.
    void batch_index_mismatch(int64 stamp) const;
    inline int batch_index_at(int64 stamp) const {
        if (PREDICT_BRANCH_NOT_TAKEN(batch_stamp != stamp))
            batch_index_mismatch(stamp);
        return batch_index;
    }

    // FUSED-OP ONLY. `(var index << 2) | visited << 1`, built by
    // FusedOp::update_ops() and read by load_fused_op() and the JIT pipeline
    // behind it. **No traversal may borrow this field.**
    //
    // It used to be a general-purpose scratch int that five unrelated
    // algorithms wrote to -- the executor's batch numbering, grad()'s gradient
    // var indices, dump_all_graphs()' node numbering, and the two topological
    // sorts -- with nothing recording whose turn it was. All five keep their
    // own storage now (misc/node_index.h, and batch_index above), so the
    // "any two traversals interleaving corrupt each other" defect is gone even
    // though the field is not.
    //
    // This one is different in kind and is why the field survives: it is not a
    // traversal marker but a mapping that has to stay valid across the whole
    // JIT pipeline (do_jit_prepare, get_loop_options, the relay manager), so
    // removing it means giving FusedOp an explicit var->index map and changing
    // three readers, one of which is tied to the generated code's struct
    // offsets. That is task 2.24, sequenced after 3.11 because it lands in the
    // same code.
    //
    // tests/structure/test_node_scratch_state.py holds this to one owner; a
    // comment on its own is what let the previous five in.
    int custom_data;
    int64 tflag = 0;
    int64 id; 
    list<input_t> _inputs;
    list<output_t> _outputs;

    int64 order() {
        if (flags.get(NodeFlags::_node_order_low)) return 0;
        if (flags.get(NodeFlags::_node_order_high)) return 1ll<<60;
        return id;
    }

    inline Node() {
        id = ++total_node;
        #ifdef NODE_MEMCHECK
        bool track = true;
        #else
        bool track = PREDICT_BRANCH_NOT_TAKEN(node_track_lived != 0);
        #endif
        if (track) {
            lived_nodes_id[id] = this;
            lived_nodes[(void*)this] = id;
            flags.set(NodeFlags::_lived_tracked, 1);
        }
        flags.set(NodeFlags::_node_order_low, node_order, 2);
    }
    inline virtual ~Node() {
        if (PREDICT_BRANCH_NOT_TAKEN(flags.get(NodeFlags::_lived_tracked))) {
            lived_nodes_id.erase(id);
            lived_nodes.erase((void*)this);
        }
        notify_node_destroyed(this);
    }

    inline Var* var() { return (Var*)this; }
    inline Op* op() { return (Op*)this; }
    inline Node* node() { return this; }
    void free();
    // this function is used for debug memory
    inline bool exist() const {
    #ifdef NODE_MEMCHECK
        return lived_nodes.count((void*)this);
    #else
        return true;
    #endif
    }
    void memcheck_all_exist() const;
    // release from counter and memory checker
    void __release();
    #define CHECK_NODE_EXIST(node) \
        ASSERT(node->exist()) << "Node("#node")" << (void*)node << "not exist."
    #define CHECK_EXIST CHECK_NODE_EXIST(this)
    #define CHECK_NODE_EXIST2(a,b) \
        CHECK_NODE_EXIST(a); CHECK_NODE_EXIST(b);
    #define CHECK_NODE_EXIST3(a,b,c) \
        CHECK_NODE_EXIST2(a,b); CHECK_NODE_EXIST(c);

    inline Caster<Node*, Node::input_t> inputs() { CHECK_EXIST; return &_inputs; }
    inline Caster<Node*, Node::output_t> outputs() { CHECK_EXIST; return &_outputs; }
    inline Node* input(uint i) {
        CHECK_EXIST;
        auto iter = _inputs.begin();
        while (i--) iter++;
        return iter->node;
    }
    inline Node* output(uint i) {
        CHECK_EXIST;
        auto iter = _outputs.begin();
        while (i--) iter++;
        return iter->node;
    }
    
    void release_inputs();
    void set_inputs(list<Node*> nodes);
    void add_inputs(const vector<Node*>& nodes);
    void add_inputs(const vector<Var*>& nodes);
    void release_forward_liveness();
    void own_forward_liveness();
    void release_backward_liveness();
    void own_backward_liveness();
    void release_pending_liveness();
    void own_pending_liveness();
    void release_both_liveness();
    void own_both_liveness();
    void finish_pending_liveness();
    void set_stop_grad();
};

struct SetupFreeBuffer {

bool outside;
inline SetupFreeBuffer() {
    outside = free_buffer_depth++ == 0;
}

inline ~SetupFreeBuffer() {
    if (outside) {
        for (int i=0; i<free_buffer.size(); i++)
            delete free_buffer[i];
        free_buffer.clear();
    }
    free_buffer_depth--;
}

};

std::ostream& operator<<(std::ostream& os, const Node* node);

} // jittor
