"""Torch serialization adapters for native complete CPU/ACL generator state.

Random values are generated by native operators. This module encodes state as
CPU ByteTensor metadata; it owns neither an RNG nor a second offset table.
"""
import secrets
import types

import numpy as np
import jittor as jt

from .context import get_install_context
from .fidelity import Fidelity, register_fidelity


def _torch():
    return get_install_context(jt).target_namespace


def _encode(payload):
    owner = _torch()
    values = np.frombuffer(payload.encode('ascii'), dtype=np.uint8).copy()
    return owner.tensor(values, dtype=owner.uint8, device='cpu')


def _decode(state):
    owner = _torch()
    if not owner.is_tensor(state):
        raise TypeError('RNG state must be a CPU ByteTensor')
    if state.dtype != owner.uint8 or state.ndim != 1 or state.device.type != 'cpu':
        raise TypeError('RNG state must be a one-dimensional CPU ByteTensor')
    values = np.asarray(state.detach().numpy())
    if values.dtype != np.uint8:
        raise TypeError('RNG state byte dtype mismatch')
    return values.tobytes().decode('ascii')


def _npu_index(device=None):
    if device is None:
        index = int(jt.core.current_device())
    elif isinstance(device, int) and not isinstance(device, bool):
        index = device
    else:
        parsed = _torch().device(device)
        if parsed.type != 'npu':
            raise ValueError('Expected an NPU device, got %s' % device)
        index = int(jt.core.current_device()) if parsed.index is None else int(parsed.index)
    count = int(jt.core.backend_device_count('acl'))
    if index < 0 or index >= count:
        raise ValueError('NPU RNG device index outside the visible ACL devices: %s' % index)
    return index


def _seed(seed):
    seed = int(seed)
    if seed < -(1 << 63) or seed > (1 << 64) - 1:
        raise RuntimeError('Overflow when unpacking NPU seed')
    return seed & ((1 << 64) - 1)


def manual_seed_cpu_and_acl(seed):
    """Torch manual_seed must not reseed Python/NumPy or inject an MPI rank offset."""
    seed = _seed(seed)
    jt.core.rng_manual_seed('cpu', seed, 0)
    if int(jt.core.backend_device_count('acl')) > 0:
        jt.core.rng_manual_seed_all('acl', seed)
    return seed


def get_cpu_rng_state():
    return _encode(jt.core.rng_state('cpu', 0))


def set_cpu_rng_state(state):
    jt.core.set_rng_state('cpu', _decode(state), 0)


def npu_get_rng_state(device='npu'):
    return _encode(jt.core.rng_state('acl', _npu_index(device)))


def npu_set_rng_state(new_state, device='npu'):
    payload = _decode(new_state)
    jt.core.set_rng_state('acl', payload, _npu_index(device))


def npu_get_rng_state_all():
    return [_encode(payload) for payload in jt.core.rng_states('acl')]


def npu_set_rng_state_all(new_states):
    # Decode every entry first; core validates every backend/device header before
    # applying any state, so a malformed later entry cannot partially restore.
    payloads = [_decode(state) for state in new_states]
    jt.core.set_rng_states('acl', payloads)


def npu_manual_seed(seed):
    jt.core.rng_manual_seed('acl', _seed(seed), _npu_index())


def npu_manual_seed_all(seed):
    jt.core.rng_manual_seed_all('acl', _seed(seed))


def npu_initial_seed():
    return int(jt.core.rng_initial_seed('acl', _npu_index()))


def npu_seed():
    npu_manual_seed(secrets.randbits(64))


def npu_seed_all():
    npu_manual_seed_all(secrets.randbits(64))


NPU_RNG_APIS = {
    'get_rng_state': npu_get_rng_state,
    'set_rng_state': npu_set_rng_state,
    'get_rng_state_all': npu_get_rng_state_all,
    'set_rng_state_all': npu_set_rng_state_all,
    'manual_seed': npu_manual_seed,
    'manual_seed_all': npu_manual_seed_all,
    'initial_seed': npu_initial_seed,
    'seed': npu_seed,
    'seed_all': npu_seed_all,
}


def install_npu_rng(npu, module_map):
    random = types.ModuleType('torch.npu.random')
    for name, implementation in NPU_RNG_APIS.items():
        setattr(npu, name, implementation)
        setattr(random, name, implementation)
    random.__all__ = tuple(NPU_RNG_APIS)
    npu.random = random
    module_map['torch.npu.random'] = random


for _name, _function in NPU_RNG_APIS.items():
    for _namespace in ('torch.npu.', 'torch.npu.random.'):
        register_fidelity(_namespace + _name, _function, Fidelity.APPROXIMATE,
            'Complete synchronized native per-visible-device ACL counter state; '
            'CPU ByteTensor serialization is versioned Jittor state, not torch_npu-compatible bytes')
del _name, _function, _namespace
