"""Explicit composition of the native Python API after core bootstrap."""

import atexit
import os

from jittor._runtime.state import RuntimeContext, RuntimeState
from . import diagnostics as _diagnostics

if "SKEY" in os.environ:
    import jittor_utils.student_queue

from .flags import (
    enable_grad,
    flag_scope,
    flags,
    no_grad,
    runtime,
    _core_flags,
    _output_requires_grad,
    _stop_grad_outputs,
)

from .var import (
    abs_,
    add_,
    amp_flags,
    arg_reduce,
    argmax,
    argmin,
    array,
    array64,
    attrs,
    cast,
    clamp,
    clamp_,
    detach,
    double,
    empty,
    erf_,
    erfinv_,
    fetch,
    flatten,
    float,
    float_auto,
    floor_int,
    format,
    full,
    full_like,
    get_len,
    grad,
    half,
    int,
    index,
    is_var,
    masked_fill,
    multiply_,
    ne,
    new_empty,
    new_full,
    new_ones,
    new_zeros,
    norm,
    normal,
    ones,
    ones_like,
    origin_reshape,
    origin_transpose,
    outer,
    permute,
    pow,
    rand,
    rand_like,
    randint,
    randint_like,
    randn,
    randn_like,
    random,
    reshape,
    sigmoid,
    sigmoid_,
    size,
    sqr,
    sqrt_,
    squeeze,
    std,
    to_bool,
    to_device,
    to_float,
    to_int,
    transpose,
    type_as,
    unsqueeze,
    var,
    view,
    vtos,
    where,
    zeros,
    zeros_like,
)

from .hooks import (
    grad_hooker,
    register_hook,
)

from .module import (
    Module,
    make_module,
)

from .function import (
    Function,
    GradHooker,
)

from .diagnostics import (
    ExitHooks,
    clean,
    dirty_fix_pytorch_runtime_error,
    display_memory_info,
    hooks,
    jittor_exit,
    liveness_info,
    log_capture_scope,
    profile_mark,
    profile_scope,
    single_process_scope,
    __single_process_scope,
)

from jittor.serialization.native import (
    dfs_to_numpy,
    load,
    save,
    safepickle,
    safeunpickle,
    _upload,
)

hooks.hook()
atexit.register(jittor_exit)


def __getattr__(name):
    if name == "single_log_capture":
        return _diagnostics.single_log_capture
    from jittor import compile_extern
    if name == "compile_extern":
        return compile_extern
    return compile_extern.distributed_state_getattr(name)


__all__ = (
    "ExitHooks",
    "Function",
    "GradHooker",
    "Module",
    "abs_",
    "add_",
    "amp_flags",
    "arg_reduce",
    "argmax",
    "argmin",
    "array",
    "array64",
    "attrs",
    "cast",
    "clamp",
    "clamp_",
    "clean",
    "detach",
    "dfs_to_numpy",
    "dirty_fix_pytorch_runtime_error",
    "display_memory_info",
    "double",
    "empty",
    "enable_grad",
    "erf_",
    "erfinv_",
    "fetch",
    "flag_scope",
    "flags",
    "flatten",
    "float",
    "float_auto",
    "floor_int",
    "format",
    "full",
    "full_like",
    "get_len",
    "grad",
    "grad_hooker",
    "half",
    "hooks",
    "int",
    "index",
    "is_var",
    "jittor_exit",
    "liveness_info",
    "load",
    "log_capture_scope",
    "make_module",
    "masked_fill",
    "multiply_",
    "ne",
    "new_empty",
    "new_full",
    "new_ones",
    "new_zeros",
    "no_grad",
    "norm",
    "normal",
    "ones",
    "ones_like",
    "origin_reshape",
    "origin_transpose",
    "outer",
    "permute",
    "pow",
    "profile_mark",
    "profile_scope",
    "rand",
    "rand_like",
    "randint",
    "randint_like",
    "randn",
    "randn_like",
    "random",
    "register_hook",
    "reshape",
    "safepickle",
    "safeunpickle",
    "save",
    "sigmoid",
    "sigmoid_",
    "single_log_capture",
    "single_process_scope",
    "size",
    "sqr",
    "sqrt_",
    "squeeze",
    "std",
    "to_bool",
    "to_device",
    "to_float",
    "to_int",
    "transpose",
    "type_as",
    "unsqueeze",
    "var",
    "view",
    "vtos",
    "where",
    "zeros",
    "zeros_like",
    "runtime",
)
