"""Static aliases for the path-loaded jittor.build.utils implementation.

This file never executes; the runtime bootstrap must remain independent of
importing jittor. Types and signatures come from their actual implementation.
"""
from typing import Tuple

# An explicit immutable type breaks the bootstrap/clean_cache import cycle.
CACHE_GROUPS: Tuple[Tuple[str, str], ...]

from jittor.build.utils import (
    BUILD_CONFIG_VARS as BUILD_CONFIG_VARS,
    LOG as LOG,
    DelayProgress as DelayProgress,
    Logwrapper as Logwrapper,
    build_config_fingerprint as build_config_fingerprint,
    cache_group_paths as cache_group_paths,
    cache_path as cache_path,
    cache_root as cache_root,
    cc as cc,
    cc_path as cc_path,
    cc_type as cc_type,
    check_cache_disk_space as check_cache_disk_space,
    check_msvc_install as check_msvc_install,
    compile_module as compile_module,
    configure_module_build as configure_module_build,
    dirty_fix_pytorch_runtime_error as dirty_fix_pytorch_runtime_error,
    do_compile as do_compile,
    download as download,
    env_or_find as env_or_find,
    env_or_try_find as env_or_try_find,
    find_cache_path as find_cache_path,
    find_exe as find_exe,
    get_build_config as get_build_config,
    get_cc_type as get_cc_type,
    get_cpu_version as get_cpu_version,
    get_int_version as get_int_version,
    get_jittor_version as get_jittor_version,
    get_py3_config_path as get_py3_config_path,
    get_py3_extension_suffix as get_py3_extension_suffix,
    get_py3_include_path as get_py3_include_path,
    get_py3_link_path as get_py3_link_path,
    get_str_hash as get_str_hash,
    get_total_mem as get_total_mem,
    get_version as get_version,
    home as home,
    import_scope as import_scope,
    in_ipynb as in_ipynb,
    is_in_ipynb as is_in_ipynb,
    limit_openmp_to_physical_cores as limit_openmp_to_physical_cores,
    lock_path as lock_path,
    msvc_path as msvc_path,
    physical_core_count as physical_core_count,
    pool_cleanup as pool_cleanup,
    pool_initializer as pool_initializer,
    pool_size as pool_size,
    resolve_exe as resolve_exe,
    run_cmd as run_cmd,
    run_cmds as run_cmds,
    save_mem_build_flags as save_mem_build_flags,
    set_home as set_home,
    short as short,
    simple_timer as simple_timer,
    target_arch_key as target_arch_key,
    time_scope as time_scope,
    try_find_exe as try_find_exe,
    try_import_jit_utils_core as try_import_jit_utils_core,
    version_dir_name as version_dir_name,
)
from jittor.build.utils.env_config import (
    build_env as build_env,
    build_flag as build_flag,
    runtime_env as runtime_env,
)
from jittor.build.utils import (
    auto_diff as auto_diff,
    backend_discovery as backend_discovery,
    backend_resources as backend_resources,
    bootstrap as bootstrap,
    build_config as build_config,
    clean_cache as clean_cache,
    compiler_flags as compiler_flags,
    config as config,
    cuda_wheel as cuda_wheel,
    env_config as env_config,
    env_manifest as env_manifest,
    install_cuda as install_cuda,
    load_pytorch as load_pytorch,
    load_pytorch_old as load_pytorch_old,
    lock as lock,
    manifest as manifest,
    misc as misc,
    preflight as preflight,
    probe as probe,
    query_cuda_cc as query_cuda_cc,
    ring_buffer as ring_buffer,
    runtime_services as runtime_services,
    save_pytorch as save_pytorch,
    student_queue as student_queue,
)
import jittor.build.utils.install_msvc as _install_msvc
install_msvc = _install_msvc
